Переделал метод Login. Добавил 2 модели LRM и User
horba/pineapple pull request #19
Opened 2017-11-21 09:33 UTC by otetsdiodor

https://github.com/horba/pineapple/issues/16

2017-12-03 21:46 UTC, horba requested changes

2017-12-03 21:46 UTC, horba commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +        public LoginResponseModel Login(User currentUser)
считать что метод должен принимать юзера не совсем корректно. пользователь это не только логин и пароль. ты можешь завести LoginModel под это

2017-12-03 21:46 UTC, horba commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +            if (currentUser.UserName == "test")
данная логика - авторизация - должна происходить на  уровне сервиса.

2017-12-04 17:41 UTC, otetsdiodor commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +            if (currentUser.UserName == "test")
На сколько я понял по формулировке задачи нужно было сделать именно так как я и сделал 
-_-

2017-12-04 22:58 UTC, horba commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +            if (currentUser.UserName == "test")
исходя из каких слов в формулировке ты сделал такой вывод?

2017-12-04 23:08 UTC, horba commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +            if (currentUser.UserName == "test")
постановка задачи оказалась не очень точной. к сожаленью, это выяснилось на этапе пулл реквеста, как часто бывает. воспринимай это не как исправление, а как уточнение.

2018-01-14 18:08 UTC, merged