Добавил модальную форму Login
horba/pineapple pull request #20
Opened 2017-11-21 10:11 UTC by otetsdiodor

https://github.com/horba/pineapple/issues/8

2017-12-03 22:20 UTC, horba requested changes

2017-12-03 22:20 UTC, horba commented on Pineapple/Pineapple/Views/Index/Index.cshtml
> +                <input class="login" id="login" type="button" value="Login" />
есть ли смысл в id?

2017-12-03 22:20 UTC, horba commented on Pineapple/Pineapple/Views/Index/Index.cshtml
> +    <div id="modal_form">
почему id, а не класс?

2017-12-03 22:20 UTC, horba commented on Pineapple/Pineapple/Views/Index/Index.cshtml
> +            <input class="login" id="login1" type="button" value="Login" />
переименуй так свои идентификаторы, чтобы избежать цифр. так, я бы переименовала твою кнопку скорее.

2017-12-03 22:20 UTC, horba commented on Pineapple/Pineapple/wwwroot/css/styles.css
> +.flex-container {
или измени название класса, или разбей на два класса. класс с таким названием подразумевает ответственность исключительно за display: flex;

2017-12-03 22:20 UTC, horba commented on Pineapple/Pineapple/wwwroot/css/ModalFormStyles.css
> +    margin-left: -150px;
почему именно такое решение?

2017-12-03 22:20 UTC, horba commented on Pineapple/Pineapple/wwwroot/css/styles.css
> +    border-radius: 10px;
возможно, это больше класс .login-button?
в идеале вообще вынести класс .button или .btn, дабы каждый не начал на свое усмотрение выбирать радиусы для своих кнопок и сохранялась общая стилистика.

2017-12-03 22:20 UTC, horba commented on Pineapple/Pineapple/wwwroot/css/styles.css
>      display: flex;
кажется класс main больше подходит под название flex-container, чем класс flex-container :D 
в идеале, если ты оставишь класс flex-container с ответственностью исключительно за дисплей флекс, то здесь можно оставить только высоту, а в темплейте вместе с мейн еще и класс flex-container применить

2017-12-04 16:43 UTC, otetsdiodor commented on Pineapple/Pineapple/Views/Index/Index.cshtml
> +                <input class="login" id="login" type="button" value="Login" />
Я на этот id вешаю обработку нажатия, погуглил не особо понял как сделать иначе

2017-12-04 16:58 UTC, otetsdiodor commented on Pineapple/Pineapple/Views/Index/Index.cshtml
> +    <div id="modal_form">
Зачем класс, если у нас только одна форма?

2017-12-04 17:19 UTC, otetsdiodor commented on Pineapple/Pineapple/wwwroot/css/styles.css
> +.flex-container {
Его роль теперь исполняет header

2017-12-04 19:40 UTC, Markiz9999 commented
Так в принципе все хорошо. Но плохо, что модальное окно не является адаптивным. Так при самом маленьком размере окна браузера (по ширине и небольшим по высоте) кнопка закрыть перестает быть видна, и подложка тоже, что не дает его закрыть. Такой размер в принципе может оказаться на каком-то из мобильных устройств. Также, правильно ли, что подложка идет отдельно от модального окна, а не как его обертка?

2017-12-04 19:41 UTC, Markiz9999 reviewed
Так в принципе все хорошо. Но плохо, что модальное окно не является адаптивным. Так при самом маленьком размере окна браузера (по ширине и небольшим по высоте) кнопка закрыть перестает быть видна, и подложка тоже, что не дает его закрыть. Такой размер в принципе может оказаться на каком-то из мобильных устройств. Также, правильно ли, что подложка идет отдельно от модального окна, а не как его обертка?

2017-12-04 22:56 UTC, horba requested changes
Не на все вопросы дан ответ. Не исправленные замечания - твое решение или не успел? если первое,  просьба, к комментарию с замечанием оставить свою обоснованную позицию, почему ты все же хочешь оставить существующую реализацию.

2017-12-04 22:56 UTC, horba commented on Pineapple/Pineapple/Views/Index/Index.cshtml
> +    <div id="modal_form">
твой вопрос не корректен.
да, тут уместен именно id. но вовсе не потому что это единственная форма. это вообще очень странная позиция.
идентификатор удобен, когда нам надо гарантировано получить именно данную ноду . на практике, такая необходимость возникает только в случае когда нужно с помощью джаваскрипт кода что-то на лету с этой нодой делать - как раз твой случай. тогда идентификатор очень полезен - по нему и поиск быстрее и результат единственный в случае успеха. 
Для стилей же принято использовать классы. 
А позиция "потому что форма одна -  позиция заученного совета со странички htmlbook про идентификаторы без попытки разобраться откуда такой совет появился.

2017-12-09 20:51 UTC, horba commented
нужно порезолвить конфликты. забери свежий девелоп и смержь его в свою ветку, разрешив конфликты.

2018-01-10 23:01 UTC, otetsdiodor commented on Pineapple/Pineapple/wwwroot/css/ModalFormStyles.css
> +    margin-left: -150px;
Я думал, что отступлю на центр экрана , а потом съеду в стороны на половину ширины формы и буду в центре.

2018-01-10 23:03 UTC, otetsdiodor commented
Смержил со свежим девелопом, но есть что подкорректировать.

2018-01-14 18:08 UTC, merged