Рефакторинг авторизации #37
horba/pineapple pull request #49
Opened 2018-02-02 20:28 UTC by Markiz9999

https://github.com/horba/pineapple/issues/37

2018-02-03 21:00 UTC, FoxCaptainFox approved these changes

2018-02-08 20:15 UTC, demosglok requested changes

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +            if (response[0] == "true")
Какое-то странное сравнение. почему сравниваем с текстовой строкой, обозначающей true?

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +                Response.Cookies.Append("session_id", response[1]);
что за respose[1]

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +                return new ObjectResult(new LoginResponseModel("true", ""));
текстовая строка обозначающая true, почему так?

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +                return new ObjectResult(new LoginResponseModel("false", response[1]));
текстовая строка для false и response[1] - это что?

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Model/LoginModel.cs
> +        public string Nick { get; set; }
Nickname или Username тогда уж. но и name было неплохо. 
Nick - слишком по простецки

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Services/UserAuth.cs
> +            string userNick = "";
username будет лучше.

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Services/UserAuth.cs
> +                return new List<string>() { "false", e.Message };
что обозначает "false"?

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Services/UserAuth.cs
> +                    FindedUser.Status = "Not find";
"Not found" было бы правильнее, но лучше делать более описательные статусы

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Services/UserAuth.cs
> +                    FindedUser.Nick = (string)reader.GetValue(1);
что такое Nick и в чем отличие от Firstname, и lastname?
обычно пишут или nickname (более просторечивый вариант) или display name

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +        <input type="text" name="nick" class="input-area" placeholder="Type your nickname" required />
если уж в placeholder'е не поленились написать nickname, то почему б в name="nick" так же не написать? не стоит экономить буквы)

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +            <label for="Nick" class="form-label">Nickname*</label>
Nickname

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +        <input type="text" name="firstName" class="input-area" id="Name" placeholder="Type your name" />
type your first name?

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +        <input type="text" name="secondName" class="input-area" id="SName" placeholder="Type your second name" />
last name более общеупотребимый термин для фамилии, чем second name

2018-02-08 20:15 UTC, demosglok commented on Pineapple/Pineapple/wwwroot/css/mainPage.css
> +    display: flex;
почему решили сделать flex, а не block?

2018-02-08 20:45 UTC, Markiz9999 commented on Pineapple/Pineapple/wwwroot/css/mainPage.css
> +    display: flex;
это свойство наверное лишнее, хоть block, хоть flex

2018-02-08 20:55 UTC, Markiz9999 commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +        <input type="text" name="secondName" class="input-area" id="SName" placeholder="Type your second name" />
поправлю

2018-02-08 20:56 UTC, Markiz9999 commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +        <input type="text" name="firstName" class="input-area" id="Name" placeholder="Type your name" />
поправлю

2018-02-08 20:56 UTC, Markiz9999 commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +            <label for="Nick" class="form-label">Nickname*</label>
поправлю

2018-02-08 21:00 UTC, Markiz9999 commented on Pineapple/Pineapple/Services/UserAuth.cs
> +                    FindedUser.Nick = (string)reader.GetValue(1);
Nick уникален. Переименую в nickname

2018-02-08 21:00 UTC, Markiz9999 commented on Pineapple/Pineapple/Services/UserAuth.cs
> +                    FindedUser.Status = "Not find";
поправлю

2018-02-08 21:02 UTC, Markiz9999 commented on Pineapple/Pineapple/Services/UserAuth.cs
> +                return new List<string>() { "false", e.Message };
обозначает что вход в аккаунт прошел неудачно

2018-02-08 21:03 UTC, Markiz9999 commented on Pineapple/Pineapple/Services/UserAuth.cs
> +            string userNick = "";
поправлю

2018-02-08 21:04 UTC, Markiz9999 commented on Pineapple/Pineapple/Model/LoginModel.cs
> +        public string Nick { get; set; }
исправил на nick так как на клиенте названо nick, и в базе столбец назван nick

2018-02-08 21:06 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +                return new ObjectResult(new LoginResponseModel("false", response[1]));
строка, которая обозначает успешен ли вход. если он успешен в response[1] - уникальная строка с id сессии, если неуспешен - то строка с ошибкой.

2018-02-08 21:07 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +                return new ObjectResult(new LoginResponseModel("true", ""));
как то так вышло, что с сервиса возвращается строковый list

2018-02-08 21:07 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +                Response.Cookies.Append("session_id", response[1]);
в response[1] - уникальная строка с id сессии, если вход неуспешен - то строка с ошибкой.

2018-02-08 21:08 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +            if (response[0] == "true")
как то так вышло, что с сервиса возвращается строковый list

2018-02-14 19:33 UTC, demosglok commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +            if (response[0] == "true")
может переделать сервис?

2018-02-14 19:34 UTC, demosglok commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +                Response.Cookies.Append("session_id", response[1]);
почему она именно в 1 индексе? может поменяется потом а мы забудем. как минимум тут бы именованную переменную или константу. а как максимум - добыть из response по имени, а не индексу

2018-02-14 19:34 UTC, demosglok commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +                return new ObjectResult(new LoginResponseModel("true", ""));
может переделать сервис?

2018-02-15 07:39 UTC, demosglok approved these changes

2018-02-15 07:39 UTC, merged