Added logout button with back-end.
horba/pineapple pull request #56
Opened 2018-02-15 23:15 UTC by FoxCaptainFox

Small refactoring of feed.

2018-02-16 10:54 UTC, Markiz9999 requested changes

2018-02-16 10:54 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/AuthController.cs
> +            //LoginResponseModel response = UserLogin.Logout();
зачем этот коментарий?

2018-02-16 10:54 UTC, Markiz9999 commented on Pineapple/Pineapple/Views/UserPage/UserPage.cshtml
> +    </div>
почему ты решил button обернуть в div?

2018-02-16 10:54 UTC, Markiz9999 commented on Pineapple/Pineapple/Views/UserPage/UserPage.cshtml
> +{
лишняя скобка - падает ошибка

2018-02-16 15:58 UTC, Markiz9999 approved these changes

2018-02-19 20:45 UTC, demosglok approved these changes

2018-02-19 20:46 UTC, merged