Добавлена автоматическая авторизация. #57
horba/pineapple pull request #59
Opened 2018-02-16 18:01 UTC by FoxCaptainFox

2018-02-19 20:45 UTC, demosglok requested changes

2018-02-19 20:45 UTC, demosglok commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +                    $.post("api/auth", data, function (response) {
а если неправильный логин-пароль? и нужно отработать этот случай?

2018-02-21 21:39 UTC, FoxCaptainFox commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +                    $.post("api/auth", data, function (response) {
Если неправильный логин/пароль, не появится окно с успешной регистрацией => не появится кнопка закрытия =>  не сработает эта функция. Более того, эта функция не загрузит не ту страницу.

2018-02-21 21:46 UTC, FoxCaptainFox commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +                    $.post("api/auth", data, function (response) {
А вот если проблемы с ДБ, оно покажет ошибку, кинет на эту функцию и будет загрузка, которая вернет обратно на главную страницу без авторизации. Т.е., просто лишняя анимация загрузки. Чтобы лишнего ничего не грузилось и не проверялось, закоммитил багфикс.

2018-02-25 23:58 UTC, demosglok requested changes

2018-02-25 23:58 UTC, demosglok commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +                    if (response.status != "wrong parameter(s)") {
а мы можем такие развернутые описания пролем пихать не в статус, а в какой-нить response.message или response.error, а status оставить простым до горя
или true/false (только не строковые, а булевые)
или какие-то статус-коды целочисленные
STATUS_OK = 1
STATUS_ERROR_PARAM=2
STATUS_ERROR_DB = 3
STATUS_ERROR_UNKNOWN=99
?

2018-02-26 04:54 UTC, FoxCaptainFox commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +                    if (response.status != "wrong parameter(s)") {
А смысл создавать именно true/false?
Это поле, которое детерминировано статусом и не будет нести какой-либо информации. Т.е., если комментарий != true, то статус false. Если ==true, то статус true.

2018-02-26 14:35 UTC, demosglok commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +                    if (response.status != "wrong parameter(s)") {
смысл такой же как статусы в http-протоколе. что б был машинно-понятный код и человеко-читаемое описание. 

сравнивать по описанию или закладываться что отсутствие описание - это признак успеха - недальновидно. у тебя описания (ошибок) потом могут вырасти в количестве и вообще на разных языках быть. не насравниваешься. а вот целочисленный код сравнить - универсально. 

да и потом может быть описание (комментарий) даже к успешному выполнению (типа "достал из кеша" или "логин ок, но истекает через 2 дня" или еще чего-то придумать)

система статус-описание где статус первичный, описание - вторично (и расширяет-объясняет статус) более гибкая и универсальная чем если сразу в стаус ложить строку и эту строку с чем-то сравнивать

2018-02-26 18:57 UTC, demosglok commented on Pineapple/Pineapple/Model/UserModel.cs
> +        public bool AllRight { get; set; }
давай их назовем 
bool Success и string Message
или int Status и string Message

2018-02-26 18:57 UTC, demosglok commented on Pineapple/Pineapple/Controllers/UserController.cs
> +            if (response.Status == "true")
у нас разве user.RegisterUser(data) возвращает строковое "true"/"false", может сделать что б он булевское возвращал true/false и тогда не надо со строками сравнивать

2018-02-26 19:01 UTC, FoxCaptainFox commented on Pineapple/Pineapple/Controllers/UserController.cs
> +            if (response.Status == "true")
Он возвращает "true" или ошибку.

2018-02-27 11:34 UTC, demosglok requested changes

2018-02-27 11:34 UTC, demosglok commented on Pineapple/Pineapple/Views/MainPage/MainPage.cshtml
> +                            $("#registerForm").data("registrtionWasSuccesful", "true");
true, not "true"

2018-02-27 11:34 UTC, demosglok commented on Pineapple/Pineapple/Services/UserAuth.cs
> +                FindedUser.Message = "Error";
лучше убрать поле Message из FindUser

2018-02-27 11:34 UTC, demosglok commented on Pineapple/Pineapple/Services/UserAuth.cs
> +                    FindedUser.Message = "Not found";
лучше убрать поле Message из FindUser

2018-02-27 11:34 UTC, demosglok commented on Pineapple/Pineapple/Model/UserModel.cs
> +        public bool Success { get; set; }
лучше убрать поле Success и Message из UserModel

2018-02-27 11:34 UTC, demosglok commented on Pineapple/Pineapple/Controllers/UserController.cs
> +            if (response.Message == "true")
не надо так. лучше пусть RegisterUser вернет true/false и в каком-то худшем случае бросит исключение, которое ты поймаешь и положишь в response.Message

2018-02-27 11:34 UTC, demosglok commented on Pineapple/Pineapple/Controllers/UserController.cs
>              if (response.Nickname == "true" && response.Email == "true" && response.FirstName == "true" && response.LastName == "true" &&
вот это сравнение всего подряд с "true" вообще выглядит очень стремно

2018-02-28 00:16 UTC, demosglok approved these changes

2018-02-28 00:16 UTC, merged