Bugfix for feature/55.
horba/pineapple pull request #62
Opened 2018-02-21 18:57 UTC by FoxCaptainFox

2018-02-25 23:55 UTC, demosglok requested changes

2018-02-25 23:55 UTC, demosglok commented on Pineapple/Pineapple/Views/UserPage/UserPage.cshtml
> +                setTimeout(function () { $("#logo").addClass("hidden"); }, 600);});
эм, не понял, зачем тут 
});
в конце?

2018-02-26 04:55 UTC, FoxCaptainFox commented on Pineapple/Pineapple/Views/UserPage/UserPage.cshtml
> +                setTimeout(function () { $("#logo").addClass("hidden"); }, 600);});
Не хватало же. Поэтому и багфикс.

2018-02-26 14:32 UTC, demosglok commented on Pineapple/Pineapple/Views/UserPage/UserPage.cshtml
> +                setTimeout(function () { $("#logo").addClass("hidden"); }, 600);});
а можешь огда отформатировать что б все красиво смотрелось. а то глядя на отформатированный код складывается впечаление что тут этот кусок лишний. 
что б понимать от какого открывающего элемента этот закрывающий. подозреваю что от $.get, но тогда нужно следующий за ним сдвинуть

2018-02-26 16:33 UTC, closed without merging