Feature/69
horba/pineapple pull request #70
Opened 2018-02-25 15:45 UTC by FoxCaptainFox

Home page связан с back-end. В ленте добавлены твиты текущего пользователя.

2018-02-25 23:42 UTC, demosglok requested changes

2018-02-25 23:42 UTC, demosglok commented on Pineapple/Pineapple/Controllers/TweetsController.cs
> +        public Object Get()
может ActionResult тут возвращать, а не Object или в этом есть какой-то дополнительный смысл? насколько я знаю, по умолчанию все методы контроллеров возвращают ActionResult ну или JsonResult для чисто json'а

2018-02-25 23:42 UTC, demosglok commented on Pineapple/Pineapple/Controllers/TweetsController.cs
> +                    List<object> response = new List<object>();
а если тут сделать Dictionary<string,string> и потом его вернуть в json, он не превратиться автоматом в json-объект?

2018-02-25 23:42 UTC, demosglok commented on Pineapple/Pineapple/wwwroot/css/main.css
> +.color-0 {
может дать цветам еще и имена, а не только 0-1-2-3-4? типа primary-color, secondary-color, highlight-color, focus-color
или что-то вроде

2018-02-25 23:42 UTC, demosglok commented on Pineapple/Pineapple/wwwroot/css/main.css
> +.background-color-0 {
то же самое

2018-02-25 23:42 UTC, demosglok commented on Pineapple/Pineapple/wwwroot/css/main.css
> +.background-color-0 {
и кстати , я б ожидал что в background-color задается css-свойство background или background-color, а не color

2018-02-25 23:42 UTC, demosglok commented on Pineapple/Pineapple/wwwroot/css/styles.css
> +    #blackout-menu {
хм, а почему на id навешен стиль, а не на класс?

2018-02-26 04:58 UTC, FoxCaptainFox commented on Pineapple/Pineapple/wwwroot/css/main.css
> +.color-0 {
Здесь и далее стили, попавшие из другой ветки. /52 или /60.

2018-02-26 05:16 UTC, FoxCaptainFox commented on Pineapple/Pineapple/Controllers/TweetsController.cs
> +        public Object Get()
Мне нужно кроме твита, дополнительно бросать никнейм автора, т.е. стандартный TweetModel не подходит.

2018-02-26 11:32 UTC, Markiz9999 commented on Pineapple/Pineapple/wwwroot/css/main.css
> +.background-color-0 {
Это я видимо забыл при копипасте заменить...

2018-02-26 14:30 UTC, demosglok commented on Pineapple/Pineapple/Controllers/TweetsController.cs
> +        public Object Get()
запили отдельную модель TweetViewModel, которая будет включать никнейм автора,  и бросай ее

2018-02-26 14:30 UTC, demosglok commented on Pineapple/Pineapple/wwwroot/css/main.css
> +.color-0 {
вы перемержили ветки между собой

2018-02-26 14:31 UTC, demosglok commented on Pineapple/Pineapple/wwwroot/css/main.css
> +.background-color-0 {
ок. повод поправить

2018-02-26 16:15 UTC, FoxCaptainFox commented on Pineapple/Pineapple/wwwroot/css/main.css
> +.color-0 {
Да.

2018-02-26 18:54 UTC, demosglok commented on Pineapple/Pineapple/Controllers/TweetsController.cs
> +                modelReader.AddTweet(new TweetModel(DateTime.UtcNow, value, idOfAuthor));
общепринятым является соглашение AuthorId для таких случаев

2018-02-26 18:54 UTC, demosglok commented on Pineapple/Pineapple/DBServices/TweetsService.cs
> +            //if (SendersOfTweets.Count == 0)
чего мы это закоментировали? если вдруг SendersOfTweets.Count == 0, то не упадет ли на
SqlCommand myCommand = new SqlCommand("SELECT * FROM dbo.Tweets WHERE idOfAuthor IN(" + SendersID + ") AND date > @ParamDate ORDER BY date DESC", DBconnection.myConnection);
                 
из-за того что будет WHERE idOfAuthor IN () после подстановки пустого списка?

2018-02-26 18:54 UTC, demosglok commented on Pineapple/Pineapple/Model/TweetViewModel.cs
> +            NicknameOfAuthor = nicknameOfAuthor;
AuthorNickname

2018-02-26 19:03 UTC, FoxCaptainFox commented on Pineapple/Pineapple/DBServices/TweetsService.cs
> +            //if (SendersOfTweets.Count == 0)
SendersID содержит как минимум id самого автора, поэтому не упадет.

2018-02-26 20:51 UTC, demosglok approved these changes

2018-02-26 20:51 UTC, merged