На странице поиска и профиля пользователя добавлены кнопки фолоу/анфолоу
horba/pineapple pull request #75
Opened 2018-02-26 20:03 UTC by Markiz9999

Мержить после поиска и страницы пользователей.

2018-02-26 20:40 UTC, demosglok requested changes

2018-02-26 20:40 UTC, demosglok commented on Pineapple/Pineapple/Controllers/TweetsController.cs
> +                        return Json(new { status = "true", tweets = response });
{status=true, message="", tweets=response}

2018-02-26 20:40 UTC, demosglok commented on Pineapple/Pineapple/Controllers/TweetsController.cs
> +                        return Json(new { status = "empty" });
{status=false, message="no tweets"} или {status=true, message="no tweets", tweets = new List<object>}

2018-02-26 20:40 UTC, demosglok commented on Pineapple/Pineapple/Controllers/TweetsController.cs
> +                    List<object> response = new List<object>();
можно ли сделать не list object'ов, а list моделек, хоть бы и TweetViewModel или что-то вроде, с нужными полями

2018-02-26 20:40 UTC, demosglok commented on Pineapple/Pineapple/Controllers/TweetsController.cs
> +                    return Json(new { status = "error" });
{status=false, message="error: wrong user"}

2018-02-26 20:40 UTC, demosglok commented on Pineapple/Pineapple/Controllers/TweetsController.cs
> +                return Json(new { status = "error" });
{status=false, message="Error: session not set"}

2018-02-27 10:23 UTC, demosglok requested changes

2018-02-27 10:23 UTC, demosglok commented on Pineapple/Pineapple/Controllers/FollowController.cs
> +                        return "You can't follow yourself";
эм, это мы из контроллера строку возвращаем? чего так?

2018-02-27 10:23 UTC, demosglok commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +                    return Json(new { FindedPeoples = usersWithFollow, status = "true", withFollow = true });
status=true, булево значение, не строковое. 

а что делает withFollow?

2018-02-27 10:23 UTC, demosglok commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +                return Json(new { status = "empty" });
status=true, message="empty" или что-то вроде. зачем это убрали и вернули "empty" в статус?

2018-02-27 10:23 UTC, demosglok commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +            return Json(new { status = true, message = "", FindedPeoples = findedusers, followButton = false } );
что такое followButton и почему она задается в контроллере?

2018-02-27 10:23 UTC, demosglok commented on Pineapple/Pineapple/Views/UserPage/SearchPage.cshtml
> +                    if (response == "true") {
if (response)
или if(response === true)

2018-02-27 10:23 UTC, demosglok commented on Pineapple/Pineapple/Views/UserPage/SearchPage.cshtml
> +                    if (response == "true") {
то же самое

2018-02-27 16:28 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +                return Json(new { status = "empty" });
Видимо вышло из-за мержа с другими ветками

2018-02-27 16:29 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +            return Json(new { status = true, message = "", FindedPeoples = findedusers, followButton = false } );
определяет нужно ли показывать кнопки подписки, если не авторизирован - не показывать

2018-02-27 16:40 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +                    return Json(new { FindedPeoples = usersWithFollow, status = "true", withFollow = true });
определяет нужно ли показывать кнопки подписки, если не авторизирован - не показывать

2018-02-27 16:50 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +            return Json(new { status = true, message = "", FindedPeoples = findedusers, followButton = false } );
Ошибся с названием, должна быть как и выше "withFollow"

2018-02-27 16:51 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/FollowController.cs
> +                        return "You can't follow yourself";
поправлю

2018-02-27 17:38 UTC, demosglok commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +                return Json(new { status = "empty" });
тогда поправить бы?

2018-02-27 17:38 UTC, demosglok commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +                        return Json(new { status = "empty" });
return new{status=false, message="empty"} (смотря что это empty значит)

2018-02-27 17:38 UTC, demosglok commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +                        return Json(new { status = "empty" });
а вообще я б не проверял тут, отдавал бы пустой список и проверял на фронтенде количество найденных юзеров

2018-02-27 17:38 UTC, demosglok commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +                    return Json(new { FindedPeoples = usersWithFollow, status = "true", withFollow = true });
может это на фронтенде проверять?

2018-02-27 17:44 UTC, Markiz9999 commented on Pineapple/Pineapple/Controllers/SearchController.cs
> +                return Json(new { status = "empty" });
поправил

2018-02-27 19:28 UTC, demosglok approved these changes

2018-02-27 19:28 UTC, merged